# Generated by Django 5.2.6 on 2025-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='day_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='driving_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='rest_stops',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='sequence',
            field=models.BigIntegerField(),
        ),
    ]
